/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca.view;

import biblioteca.controller.TelaRegistrarDevolucaoController;
import java.awt.Component;
import java.text.ParseException;
import java.util.ArrayList;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.Objects;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

public class TelaRegistrarDevolucao extends javax.swing.JFrame {

    /**
     * Creates new form TelaRegistrarDevolucao
     */
    public TelaRegistrarDevolucao() {
        initComponents();
    }
    //Carrega dados
    public  TelaRegistrarDevolucao(String id) {
        initComponents();
        formatarData ();
        
        idEmprestimo.setVisible(false);
        idEmprestimo.setText(id);
        
        ArrayList<String> dados= new ArrayList<>();
        dados= TelaRegistrarDevolucaoController.dadosEmprestimo(id);  
        idUsuario.setVisible(false);
        idUsuario.setText(dados.get(1));
        usuario.setText(dados.get(2));
        livro.setText(dados.get(3));
        String editaData= dados.get(4);
        int ano = Integer.parseInt(editaData.substring(0,4));
        int mes = Integer.parseInt(editaData.substring(5,7));
        int dia = Integer.parseInt(editaData.substring(8,10));
        editaData = editaData.substring(8,10) + editaData.substring(5,7) + editaData.substring(0,4);
        dataDevolucao.setText(editaData);
        valorPago.setText("0,00");
        totalMulta.setText("0,00");
        
        LocalDateTime dataCadastro = LocalDateTime.of(ano,mes,dia,0,0);
        LocalDateTime hoje = LocalDateTime.now();

        //calcula diferença de dias
        long dias = ChronoUnit.DAYS.between(dataCadastro, hoje);
        
        String editaHoje = hoje.toString().substring(0, 10);
        editaHoje = editaHoje.substring(8,10) + "/" + editaHoje.substring(5,7) + "/" + editaHoje.substring(0,4);
        dataAtual.setText(editaHoje);
        
        double calcMultaAtraso = 0;
        if (dias > 0){
            calcMultaAtraso = dias * 0.15;
            
            
            multaAtraso.setText(String.format("%.2f", calcMultaAtraso));
            totalMulta.setText(String.format("%.2f", calcMultaAtraso));
        }
        else {
            multaAtraso.setText("0.00");
        }
        dataDevolucao.setEditable(false);
        usuario.setEditable(false);
        livro.setEditable(false);
        dataDevolucao.setEditable(false);
        multaAtraso.setEditable(false);
        totalMulta.setEditable(false);
        descricaoMulta.setEditable(false);
        valorPago.setText("0,00");
        if (calcMultaAtraso > 0){
            valorPago.setEditable(true);
        }
        else {
            valorPago.setEditable(false);
        }
        
    }

    private void formatarData () {
        try {
            MaskFormatter mask = new MaskFormatter ("##/##/####");
            mask.install(dataAtual);
            mask.install(dataDevolucao);
            
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao formatar campo de texto", "Erro", JOptionPane.ERROR);
        }
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pago = new javax.swing.JLabel();
        confirmarDevolucao = new javax.swing.JButton();
        totalMulta = new javax.swing.JTextField();
        multaDeterioracao = new javax.swing.JTextField();
        multaAtraso = new javax.swing.JTextField();
        livro = new javax.swing.JTextField();
        usuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dataDevolucao = new javax.swing.JFormattedTextField();
        dataAtual = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        descricaoMulta = new javax.swing.JTextField();
        valorPago = new javax.swing.JTextField();
        header = new javax.swing.JPanel();
        mgLogo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idEmprestimo = new javax.swing.JTextField();
        idUsuario = new javax.swing.JTextField();
        voltar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Devolução");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Devolução", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setText("Usuário");

        jLabel2.setText("Livro");

        jLabel3.setText("Data máxima devolução");

        jLabel4.setText("Multa Atraso");

        jLabel5.setText("Multa por deterioração");

        jLabel6.setText("Total Multa");

        pago.setText("Valor Pago");

        confirmarDevolucao.setText("Confirmar Devolução");
        confirmarDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarDevolucaoActionPerformed(evt);
            }
        });

        multaDeterioracao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                multaDeterioracaoKeyReleased(evt);
            }
        });

        jLabel8.setText("Data atual");

        jLabel9.setText("Motivo Multa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pago)
                        .addComponent(jLabel6)))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalMulta)
                    .addComponent(multaAtraso)
                    .addComponent(multaDeterioracao)
                    .addComponent(confirmarDevolucao, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(livro)
                    .addComponent(usuario)
                    .addComponent(dataAtual)
                    .addComponent(dataDevolucao)
                    .addComponent(descricaoMulta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(valorPago))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(livro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(dataAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(multaAtraso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(multaDeterioracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(descricaoMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(totalMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pago)
                    .addComponent(valorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmarDevolucao)
                .addGap(41, 41, 41))
        );

        header.setBackground(new java.awt.Color(255, 255, 255));

        mgLogo.setBackground(new java.awt.Color(255, 255, 255));
        mgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon.png"))); // NOI18N
        mgLogo.setToolTipText("");
        mgLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Empréstimos > Registrar Devolução");

        idEmprestimo.setMinimumSize(new java.awt.Dimension(0, 0));
        idEmprestimo.setName(""); // NOI18N

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mgLogo)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(idEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(idUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mgLogo)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(idEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(voltar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(voltar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
    }//GEN-LAST:event_jButton2ActionPerformed
  private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
    }        
    private void confirmarDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarDevolucaoActionPerformed
        
        Double totalMul = Double.parseDouble(totalMulta.getText().replace(",","."));
        Double valPago = Double.parseDouble(valorPago.getText().replace(",","."));
     
            if (TelaRegistrarDevolucaoController.registrarDevolucao(idEmprestimo.getText())) { 
                Component frame = null;
                JOptionPane.showMessageDialog(frame, "Devolução registrada com sucesso!");
            }
        if (totalMul > 0){
             if (Objects.equals(valPago, totalMul)){
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Multa paga!");
        }
        else {
            Double valDevedor = totalMul - valPago;
            String valor = String.format("%.2f", valDevedor);
            valor = valor.replace(",",".");
            if (valDevedor<0){
                Component frame = null;
                JOptionPane.showMessageDialog(frame, "Multa paga!");
            }
            else if (TelaRegistrarDevolucaoController.bloquearUsuario(idEmprestimo.getText(), idUsuario.getText(), 
                   valor, descricaoMulta.getText())) {                
                Component frame = null;
                JOptionPane.showMessageDialog(frame, "Usuário bloqueado por falta de pagamento!");   
            }
        }
        }
       
        
        TelaEmprestimos tela = new TelaEmprestimos();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_confirmarDevolucaoActionPerformed

    //Abre gerenciar empréstimos e fecha a atual
    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        TelaEmprestimos tela = new TelaEmprestimos();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    //Atualiza valor total da multa, conforme valor da multa por deterioração
    private void multaDeterioracaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_multaDeterioracaoKeyReleased
        if (multaDeterioracao.getText().length()>0){
            Double multaDet = Double.parseDouble(multaDeterioracao.getText().replace(",","."));
              Double somaFinal = multaDet + Double.parseDouble(multaAtraso.getText().replace(",","."));
              totalMulta.setText(String.format("%.2f", somaFinal));
              descricaoMulta.setEditable(true);
              valorPago.setEditable(true);
        }
              
    }//GEN-LAST:event_multaDeterioracaoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrarDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrarDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrarDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrarDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRegistrarDevolucao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmarDevolucao;
    private javax.swing.JFormattedTextField dataAtual;
    private javax.swing.JFormattedTextField dataDevolucao;
    private javax.swing.JTextField descricaoMulta;
    private javax.swing.JPanel header;
    private javax.swing.JTextField idEmprestimo;
    private javax.swing.JTextField idUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField livro;
    private javax.swing.JLabel mgLogo;
    private javax.swing.JTextField multaAtraso;
    private javax.swing.JTextField multaDeterioracao;
    private javax.swing.JLabel pago;
    private javax.swing.JTextField totalMulta;
    private javax.swing.JTextField usuario;
    private javax.swing.JTextField valorPago;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
